[package]
name = "set_abort_panic"
version = "0.1.0"
edition = "2021"

[dependencies]

# 本部分设置仅在debug模式下生效
# [profile.debug]

# 本部分设置仅在release模式下生效
[profile.release]
# 在release模式下,当panic时直接终止程序
panic = "abort"